[server]
enableStaticServing = true

[theme]
primaryColor = "#000000"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
sidebarBackgroundColor = "#000000"
sidebarSecondaryBackgroundColor = "#000000"
sidebarTextColor = "#ffffff"
textColor = "#000000"
linkColor = "#000000"
borderColor = "#CBCED7"
showBorderAroundInputs = true
roundness = 0
font = "GuardianSans"
baseFontSize = 16


[[theme.fontFaces]]
url = "app/static/guardian-sans/GuardianSansLight.otf"
family = "GuardianSans"
weight = 300

[[theme.fontFaces]]
url = "app/static/guardian-sans/GuardianSansRegular.otf"
family = "GuardianSans"
weight = 400

[[theme.fontFaces]]
url = "app/static/guardian-sans/GuardianSansMedium.otf"
family = "GuardianSans"
weight = 500

[[theme.fontFaces]]
url = "app/static/guardian-sans/GuardianSansSemibold.otf"
family = "GuardianSans"
weight = 600

[[theme.fontFaces]]
url = "app/static/guardian-sans/GuardianSansBold.otf"
family = "GuardianSans"
weight = 700


[[theme.fontFaces]]
url = "app/static/Sanomat Web Regular Regular.ttf"
family = "Sanomat"


[[theme.fontFaces]]
url = "static/tiempos/TestTiemposFine-Light.otf"
family = "Tiempos"
weight = 300

[[theme.fontFaces]]
url = "static/tiempos/TestTiemposFine-Regular.otf"
family = "Tiempos"
weight = 400

[[theme.fontFaces]]
url = "static/tiempos/TestTiemposFine-Medium.otf"
family = "Tiempos"
weight = 500

[[theme.fontFaces]]
url = "static/tiempos/TestTiemposFine-Semibold.otf"
family = "Tiempos"
weight = 600

[[theme.fontFaces]]
url = "static/tiempos/TestTiemposFine-Bold.otf"
family = "Tiempos"
weight = 700

[[theme.fontFaces]]
url = "static/tiempos/TestTiemposFine-Black.otf"
family = "Tiempos"
weight = 900
