[server]
enableStaticServing = true

[theme]
primaryColor = "#000000"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
sidebarBackgroundColor = "#000000"
sidebarSecondaryBackgroundColor = "#000000"
sidebarTextColor = "#ffffff"
textColor = "#000000"
linkColor = "#000000"
borderColor = "#CBCED7"
showBorderAroundInputs = true
roundness = 0
font = "GuardianSans"

[[theme.fontFaces]]
url = "app/static/guardian-sans/GuardianSansRegular.otf"
family = "GuardianSans"
style = "normal"

