[server]
enableStaticServing = true

[theme]
# Blackstone
# What's missing/doesn't look great:
# - serif font (Sanomat) for headings and a few things like st.metric
# - finding a border color that works both for the main area and the sidebar was tricky -> would be nice to separate these out
# - sidebar link color would need to be separate, white
# - selectbox hover color is not visible. would also need to be set separately in main area and sidebar
# - black primary color leads to problems in the sidebar, e.g. button borders disappear. maybe we'd need a separate primary color in the sidebar (white)?
# - code background is not visible
# - dataframe border color is quite light, might want to make darker
primaryColor = "#000000"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
sidebarBackgroundColor = "#000000"
sidebarSecondaryBackgroundColor = "#000000"
sidebarTextColor = "#ffffff"
textColor = "#000000"
linkColor = "#000000"
borderColor = "#CBCED7"
showBorderAroundInputs = true
roundness = 0
font = "GuardianSans"

[[theme.fontFaces]]
url = "app/static/guardian-sans/GuardianSansRegular.otf"
family = "GuardianSans"
style = "normal"

